Для успішного виконання домашки використовуйте документацію [NumPy](https://numpy.org/doc/stable/).

Зверніть увагу на такі методи `numpy`:
* *arange*
* *zeros*
* *ones*
* *full*
* *nonzero*
* *eye*
* *random*
* *sort*
* *sum*
* *min*
* *mean*

In [2]:
import numpy as np

In [4]:
# Завдання 1: Створити масив розміром 3x3 зі значеннями від 0 до 8
# Hints: np.arange
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
# Завдання 2: Створити вектор розміром 10, заповнений нулями
arr2 = np.zeros(10, dtype=int)
arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [71]:
# Завдання 3: Створити вектор розміром 10, заповнений одиницями
arr3 = np.ones(10, dtype=int)
arr3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
# Завдання 4: Створити вектор розміром 10, заповнений значеннями 5
# Hints: np.full
arr4 = np.full(10,5)
arr4

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [20]:
# Завдання 5: Створити вектор з числами від 10 до 49
arr5 = np.arange(10,50)
arr5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [23]:
# Завдання 6: Реверсувати порядок елементів вектора з завдання 5
arr6 = np.flip(arr5)
arr6

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [32]:
# Завдання 7: Створити 9x9 матрицю зі значеннями від 0 до 80
# Hints: np.arange
arr7 = np.arange(0, 81).reshape(9,9)
arr7

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [73]:
# Завдання 8: Знайти індекси ненульових елементів вектора [1,2,0,0,4,0]
# Hints: np.nonzero
arr8 = np.array([1,2,0,0,4,0]).nonzero()
arr8

(array([0, 1, 4]),)

In [5]:
# Завдання 9: Створити одиничну матрицю розміром 3x3
# Hints: np.eye
arr9 = np.eye(3)
arr9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
# Завдання 10: Створити випадковий вектор розміром 10 та відсортувати його
arr10_sorted = np.random.randint(100, size=10)
arr10_sorted.sort()
arr10_sorted

array([ 5,  7, 14, 18, 21, 25, 59, 68, 73, 92])

In [43]:
# Завдання 11: Створити матрицю 5x5 з випадковими цілими числами в діапазоні від 0 до 10
arr11 = np.random.randint(0,10,size=(5,5))
arr11

array([[5, 9, 7, 8, 3],
       [9, 1, 2, 7, 1],
       [3, 7, 1, 1, 2],
       [1, 9, 8, 7, 6],
       [9, 8, 5, 1, 3]])

In [44]:
# Завдання 12: Обчислити суму всіх елементів матриці з завдання 11
arr11_sum = arr11.sum()
arr11_sum

123

In [48]:
# Завдання 13: Знайти найменше значення в кожному рядку матриці з завдання 11
arr11_min_row = arr11.min(axis=1)
arr11_min_row

array([3, 1, 1, 1, 1])

In [49]:
# Завдання 14: Обчислити середнє значення кожного стовпця матриці з завдання 11
arr11_mean_col = arr11.mean()
arr11_mean_col

4.92

In [59]:
# Завдання 15: Створити випадковий вектор розміром 15 та замінити максимальне значення на -1
# Hints: np.argmax
arr15 = np.random.randint(20, size=15)
arr15[arr15.argmax()] = -1
arr15

array([14, 16,  4,  2,  2, 11,  3, 16, 11,  1, 10,  3, 15,  0, -1])

In [65]:
# Завдання 16: Перетворити випадковий вектор розміром 10 в матрицю розміром 2x5
arr16 = np.arange(0,10).reshape(2,5)
arr16

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
# Завдання 17: Знайти середнє значення елементів матриці з завдання 16
arr16_mean = arr16.mean()
arr16_mean

4.5